# Uncomment this line to define a global platform for your project
# platform :ios, '6.0'

source 'https://github.com/CocoaPods/Specs.git'

target 'Gautam Mittal' do

pod 'Wit', '~> 4.1.0'

end

target 'Gautam MittalTests' do

end

